name: Simple CI with Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Get code
        uses: actions/checkout@v4   

      - name: Build docker image
        run: docker build -t myapp:test -f Dockerfile.dev .

      - name: Run tests in container
        run: docker run --rm myapp:test npm test -- --watchAll=false
